from datetime import datetime

from app.engine.context import parse_context
from app.engine.recommender import feasible_places, recommend_itineraries
from app.models.schemas import (
    Budget,
    ContextParseRequest,
    Coordinates,
    GroupMode,
    Interest,
    Mood,
    WeatherCondition,
)


def test_recommendations_return_exactly_three_distinct_options():
    context = parse_context(
        ContextParseRequest(
            location=Coordinates(lat=40.7359, lng=-73.9911),
            mood=Mood.calm,
            budget=Budget.low,
            available_minutes=100,
            local_datetime=datetime(2026, 5, 12, 16, 0),
        )
    )

    recommendations = recommend_itineraries(context)

    assert len(recommendations) == 3
    assert len({option.id for option in recommendations}) == 3
    assert all(len(option.stops) >= 2 for option in recommendations)


def test_rain_context_prefers_indoor_feasible_places():
    context = parse_context(
        ContextParseRequest(
            location=Coordinates(lat=40.7359, lng=-73.9911),
            weather=WeatherCondition.rain,
            budget=Budget.medium,
            local_datetime=datetime(2026, 5, 12, 16, 0),
        )
    )

    candidates = feasible_places(context, [])
    assert candidates == []

    recommendations = recommend_itineraries(context)
    indoor_stops = [stop.indoor for option in recommendations for stop in option.stops]
    assert sum(indoor_stops) >= len(indoor_stops) - 1


def test_duration_stays_near_budget_for_short_context():
    context = parse_context(
        ContextParseRequest(
            location=Coordinates(lat=40.7359, lng=-73.9911),
            available_minutes=60,
            budget=Budget.low,
            local_datetime=datetime(2026, 5, 12, 15, 0),
        )
    )

    recommendations = recommend_itineraries(context)

    assert all(option.estimated_duration_minutes <= 80 for option in recommendations)


def test_late_night_context_still_returns_three_with_hour_caveat():
    context = parse_context(
        ContextParseRequest(
            location=Coordinates(lat=40.7359, lng=-73.9911),
            available_minutes=90,
            weather=WeatherCondition.rain,
            mood=Mood.calm,
            budget=Budget.low,
            local_datetime=datetime(2026, 5, 12, 2, 30),
        )
    )

    recommendations = recommend_itineraries(context)

    assert len(recommendations) == 3
    assert any(
        "Check live hours" in caveat
        for option in recommendations
        for caveat in option.caveats
    )


def test_recommendations_include_algorithm_agent_and_critic_scores():
    context = parse_context(
        ContextParseRequest(
            location=Coordinates(lat=40.7359, lng=-73.9911),
            mood=Mood.curious,
            interests=[Interest.art, Interest.architecture],
            budget=Budget.medium,
            local_datetime=datetime(2026, 5, 12, 16, 0),
        )
    )

    recommendation = recommend_itineraries(context)[0]

    assert recommendation.scores["algorithmic_score"] > 0
    assert recommendation.scores["agent_approval"] > 0
    assert recommendation.scores["llm_critique"] > 0
    assert "Generated by candidate search" in recommendation.explanation


def test_different_personalities_change_the_slate():
    shared = {
        "location": Coordinates(lat=40.7359, lng=-73.9911),
        "available_minutes": 100,
        "budget": Budget.low,
        "local_datetime": datetime(2026, 5, 12, 16, 0),
    }
    calm = parse_context(
        ContextParseRequest(
            **shared,
            mood=Mood.calm,
            interests=[Interest.books, Interest.cafes],
            note="quiet books low effort",
        )
    )
    hungry = parse_context(
        ContextParseRequest(
            **shared,
            mood=Mood.hungry,
            interests=[Interest.food],
            group_mode=GroupMode.group,
            note="food with friends lively",
        )
    )

    calm_ids = {option.id for option in recommend_itineraries(calm)}
    hungry_ids = {option.id for option in recommend_itineraries(hungry)}

    assert calm_ids != hungry_ids
